// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using datagenerator.core.repository;

#nullable disable

namespace datagenerator.core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("datagenerator.core.models.Item", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификатор");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Признак удаленного предмета");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Имя предмета");

                    b.Property<Guid>("TemplateID")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Ссылка на шаблон");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TemplateID");

                    b.ToTable("ITEMS");
                });

            modelBuilder.Entity("datagenerator.core.models.Template", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификатор");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Признак удаленного шаблона");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComment("Имя шаблона");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TEMPLATES");
                });

            modelBuilder.Entity("datagenerator.core.models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификатор");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Признак удаленного пользователя");

                    b.Property<string>("Nickname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("Псевдоним пользователя");

                    b.Property<Guid>("UserDataID")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Ссылка на пользовательские данные");

                    b.HasKey("ID");

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasFilter("[Nickname] IS NOT NULL");

                    b.HasIndex("UserDataID")
                        .IsUnique();

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("datagenerator.core.models.UserData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификатор");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Хешированный пароль");

                    b.HasKey("ID");

                    b.ToTable("USERDATA");
                });

            modelBuilder.Entity("datagenerator.core.models.Item", b =>
                {
                    b.HasOne("datagenerator.core.models.Template", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("datagenerator.core.models.User", b =>
                {
                    b.HasOne("datagenerator.core.models.UserData", "UserData")
                        .WithOne("User")
                        .HasForeignKey("datagenerator.core.models.User", "UserDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("datagenerator.core.models.Template", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("datagenerator.core.models.UserData", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
